/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        primary: "#EA580C",
        secondary: "#C2410C",
        "on-primary": "#FFFFFF",
        "on-secondary": "#FFFFFF",
        surface: "#FFFFFF",
        "surface-variant": "#F3F4F6",
        "on-surface": "#0F172A",
        "on-surface-variant": "#475569",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#F8FAFC",
        "surface-container": "#F1F5F9",
        "surface-container-high": "#E2E8F0",
        "surface-container-highest": "#CBD5E1",
        "inverse-surface": "#0F172A",
        "inverse-on-surface": "#F8FAFC",
        "orange-light": "#FFEDD5",
        "orange-subtle": "#FFF7ED",
        "outline-variant": "#E2E8F0",
        "border-technical": "#E2E8F0",

        "primary-container": "#F97316",
        "on-primary-container": "#582200",
        "primary-fixed": "#FFDBCA",
        "primary-fixed-dim": "#FFB690",
        "on-primary-fixed": "#341100",
        "on-primary-fixed-variant": "#783200",

        "secondary-container": "#FD651E",
        "on-secondary-container": "#571A00",
        "secondary-fixed": "#FFDBCE",
        "secondary-fixed-dim": "#FFB599",
        "on-secondary-fixed": "#370E00",
        "on-secondary-fixed-variant": "#7F2B00",

        tertiary: "#855316",
        "on-tertiary": "#FFFFFF",
        "tertiary-container": "#CA8E4C",
        "on-tertiary-container": "#4C2A00",
        "tertiary-fixed": "#FFDCBD",
        "tertiary-fixed-dim": "#FCB973",
        "on-tertiary-fixed": "#2C1600",
        "on-tertiary-fixed-variant": "#683C00",

        "surface-bright": "#FFF8F5",
        "surface-dim": "#E2D8D2",
        outline: "#8C7164",

        error: "#BA1A1A",
        "on-error": "#FFFFFF",
        "error-container": "#FFDAD6",
        "on-error-container": "#93000A",
      },
      spacing: {
        "gutter-mobile": "1rem",
        "gutter-desktop": "1.5rem",
        "unit-xs": "0.5rem",
        "unit-sm": "1rem",
        "unit-md": "1.5rem",

        "container-max": "80rem",
        "space-xxs": "0.125rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-base": "1rem",
        "space-lg": "1.25rem",
        "space-xl": "1.5rem",
        "space-2xl": "2rem",
        "space-3xl": "2.5rem",
        "space-4xl": "3rem",
        "space-5xl": "4rem",
      },
      fontFamily: {
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": [
          "40px",
          { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "display-lg-mobile": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": [
          "28px",
          { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "700" },
        ],
        "headline-md": [
          "22px",
          { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-sm": [
          "18px",
          { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" },
        ],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-lg": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.005em", fontWeight: "600" },
        ],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "600" },
        ],
        "label-sm": [
          "11px",
          { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" },
        ],
      },
      boxShadow: {
        "ambient-shadow": "0 4px 20px -2px rgba(0, 0, 0, 0.05)",
        "ambient-shadow-lg": "0 10px 30px -4px rgba(0, 0, 0, 0.1)",
      },
    },
  },
  plugins: [],
};
